source: "./docs"

baseurl: "/"
url: "https://docs.cnpja.com.br"

remote_theme: pmarsceill/just-the-docs@16c18c10209bcf36811201968fe90153f3d45f8f
color_scheme: "cnpja"

search_enabled: true
heading_anchors: true

title: "Documentação"
footer_content: "&copy; 2020 CNPJá Tecnologia LTDA"

plugins:
  - jekyll-sitemap
